# PROJECT 3 - PART THREE
## EDA OF KETO AND WINE DATAFRAMES

Overview:

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline

import nltk
import json
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import RegexpTokenizer
import regex as re

from nltk.corpus import stopwords
from bs4 import BeautifulSoup
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.linear_model import LogisticRegression
# Import CountVectorizer and TFIDFVectorizer from feature_extraction.text.
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

**ADDRESSING THE KETO DATAFRAME**

In [2]:
keto= pd.read_csv('keto_push_clean.csv')
keto.drop(columns = ['Unnamed: 0'],inplace=True)
keto.head()

,title,selftext,subreddit,created_utc,author,num_comments,score,is_self,timestamp
0,It's been a hot minute,I keep getting off track when it comes to keto...,keto,1580160840,bbwsoontobebw,5,1,True,2020-01-27
1,Type 1 Diabetes on Keto,"Hello, I’m beginning my second month of keto. ...",keto,1580160905,iWantNotToWant,10,1,True,2020-01-27
2,"Week 3,5 and intense cravings for bread and rice","Week 3,5 and I am having intense cravings for ...",keto,1580161118,littleboo2theboo,10,1,True,2020-01-27
3,12-Week Challenge at the gym and looking for t...,"Hi guys,\n\nI am looking for some advice. I di...",keto,1580161503,chow_shepard,4,1,True,2020-01-27
4,"Does never going ""Full Keto"" hurt my health?",Hello!\n\nI'm a active highschooler who avoids...,keto,1580161639,OrganizingChaosBrb,3,1,True,2020-01-27

*FOCUS ON KEY COLUMNS*

In [3]:
keto.drop(columns=['created_utc','author','num_comments','score','is_self','timestamp'], inplace=True)

In [4]:
keto.head()

,title,selftext,subreddit
0,It's been a hot minute,I keep getting off track when it comes to keto...,keto
1,Type 1 Diabetes on Keto,"Hello, I’m beginning my second month of keto. ...",keto
2,"Week 3,5 and intense cravings for bread and rice","Week 3,5 and I am having intense cravings for ...",keto
3,12-Week Challenge at the gym and looking for t...,"Hi guys,\n\nI am looking for some advice. I di...",keto
4,"Does never going ""Full Keto"" hurt my health?",Hello!\n\nI'm a active highschooler who avoids...,keto

*CONVERT SUBREDDIT VALUE FOR KETO TO 1*

In [5]:
#subreddit is my target, which I will map to 0 for keto
keto['subreddit']=keto['subreddit'].map({'keto':1})

In [6]:
keto.head()

,title,selftext,subreddit
0,It's been a hot minute,I keep getting off track when it comes to keto...,1
1,Type 1 Diabetes on Keto,"Hello, I’m beginning my second month of keto. ...",1
2,"Week 3,5 and intense cravings for bread and rice","Week 3,5 and I am having intense cravings for ...",1
3,12-Week Challenge at the gym and looking for t...,"Hi guys,\n\nI am looking for some advice. I di...",1
4,"Does never going ""Full Keto"" hurt my health?",Hello!\n\nI'm a active highschooler who avoids...,1

*COMBINE TITLE AND SELFTEXT COLUMNS TO PREP FOR VECTORIZER*

In [7]:
keto['titleself']=keto['title']+' '+keto['selftext']
keto.head()

,title,selftext,subreddit,titleself
0,It's been a hot minute,I keep getting off track when it comes to keto...,1,It's been a hot minute I keep getting off trac...
1,Type 1 Diabetes on Keto,"Hello, I’m beginning my second month of keto. ...",1,"Type 1 Diabetes on Keto Hello, I’m beginning m..."
2,"Week 3,5 and intense cravings for bread and rice","Week 3,5 and I am having intense cravings for ...",1,"Week 3,5 and intense cravings for bread and ri..."
3,12-Week Challenge at the gym and looking for t...,"Hi guys,\n\nI am looking for some advice. I di...",1,12-Week Challenge at the gym and looking for t...
4,"Does never going ""Full Keto"" hurt my health?",Hello!\n\nI'm a active highschooler who avoids...,1,"Does never going ""Full Keto"" hurt my health? H..."

In [8]:
features = ['titleself']
X=keto[features]
y=keto.subreddit

In [9]:
# Assess y
y.value_counts()

1    7894
Name: subreddit, dtype: int64

In [10]:
# Split the data into the training and testing sets.
X_train, X_test, y_train, y_test = train_test_split(X,
                                                   y,
                                                    test_size=0.33,
                                                    stratify=y,
                                                   random_state=42)

*APPLY VECTORIZER*

In [11]:
cvec=CountVectorizer(stop_words={'english'},max_features=1000,ngram_range=(1,2))

In [12]:
cvec.fit(keto['titleself'])

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=1000, min_df=1,
                ngram_range=(1, 2), preprocessor=None, stop_words={'english'},
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [13]:
print(cvec.vocabulary_)

{'it': 435, 'been': 113, 'keep': 454, 'getting': 321, 'off': 609, 'track': 885, 'when': 948, 'comes': 179, 'to': 851, 'keto': 457, 'my': 557, 'heart': 364, 'know': 474, 'how': 384, 'much': 555, 'weight': 934, 'could': 187, 'have': 351, 'lost': 511, 'if': 397, 'didn': 211, 'good': 332, 've': 907, 'the': 797, 'for': 299, 'and': 50, 'now': 590, 'back': 99, 'on': 617, 'me': 532, 'it been': 438, 'to keto': 862, 'how much': 386, 'have lost': 354, 've been': 908, 'off the': 610, 'the keto': 806, 'and now': 63, 'back on': 102, 'type': 894, 'diabetes': 209, 'hello': 366, 'beginning': 117, 'second': 705, 'month': 544, 'of': 596, 'at': 90, 'was': 918, 'amazing': 44, 'insulin': 416, 'went': 939, 'down': 233, 'like': 492, 'but': 137, 'high': 374, 'out': 634, 'no': 583, 'reason': 681, 'is': 423, 'this': 831, 'normal': 585, 'did': 210, 'end': 252, 'would': 980, 'love': 516, 'your': 998, 'on keto': 620, 'of keto': 601, 'at the': 94, 'it was': 448, 'out of': 635, 'is this': 430, 'week': 928, 'cravings': 193, 'bread': 133, 'rice': 691, 'am': 42, 'having': 358, 'so': 729, 'far': 273, 'stuck': 760, 'diet': 212, 'do': 218, 'go': 324, 'over': 636, 'calories': 151, 'not': 586, 'with': 961, 'non': 584, 'food': 297, 'should': 717, 'myself': 570, 'cheat': 165, 'meal': 535, 'or': 629, 'can': 153, 'make': 525, 'stop': 753, 'week and': 929, 'and am': 51, 'so far': 730, 'to my': 867, 'my diet': 560, 'over the': 637, 'but not': 142, '12': 3, 'gym': 340, 'looking': 503, 'tips': 849, 'hi': 373, 'guys': 338, 'some': 735, 'advice': 26, 'read': 676, 'faq': 272, 'too': 880, 'feel': 280, 'free': 309, 'there': 821, 'something': 738, 'had': 341, 'lot': 512, 'success': 763, 'few': 285, 'years': 987, 'ago': 29, 'got': 333, 'lazy': 481, 'gained': 317, 'all': 32, 'even': 259, 'though': 840, 'never': 577, 'up': 898, 'here': 371, 'again': 28, 'anyway': 81, 'just': 453, 'in': 405, 'year': 986, 'really': 680, 'want': 914, 'issue': 433, 'eat': 246, 'small': 726, 'meals': 536, 'day': 202, 'that': 787, 'feels': 283, 'since': 722, '18': 6, 'results': 690, 'need': 571, 'be': 108, 'days': 204, 'three': 844, 'you': 991, 'think': 829, 'eating': 247, 'macros': 522, 'staying': 748, 'within': 967, 'right': 692, 'during': 241, 'question': 669, 'isn': 432, 'about': 18, 'what': 942, 'muscle': 556, 'lose': 506, 'once': 624, 'any': 72, 'appreciated': 84, 'community': 181, 'always': 41, 'great': 335, 'forward': 307, 'as': 87, 'more': 548, 'the gym': 805, 'looking for': 504, 'for some': 305, 'the faq': 803, 'lot of': 513, 'with keto': 963, 'years ago': 988, 'it all': 436, 'at my': 93, 'want to': 915, 'keto is': 465, 'is the': 428, 'to the': 874, 'the diet': 801, 'day and': 203, 'and that': 65, 'keto and': 458, 'and if': 57, 'need to': 573, 'to be': 852, 'to keep': 861, 'with the': 965, 'do you': 220, 'my macros': 565, 'and had': 55, 'my question': 567, 'so much': 731, 'to eat': 854, 'lose weight': 507, 'any advice': 73, 'does': 222, 'going': 329, 'full': 315, 'health': 361, 'who': 954, 'past': 642, 'try': 888, 'point': 652, 'currently': 198, 'doing': 225, 'intermittent': 418, 'fasting': 275, 'while': 953, 'trying': 890, 'mostly': 553, 'whole': 955, 'foods': 298, 'thing': 827, 'basically': 107, 'only': 627, 'meat': 538, 'veggies': 912, 'often': 611, 'cook': 185, 'coconut': 174, 'oil': 612, 'things': 828, 'times': 848, 'friends': 311, 'get': 319, 'pizza': 648, 'maybe': 531, 'coffee': 175, 'say': 701, 'bad': 105, 'completely': 182, 'carbs': 157, 'life': 490, 'an': 49, 'll': 497, 'also': 40, 'mental': 539, 'big': 125, 'part': 641, 'may': 530, 'won': 969, 'their': 818, 'because': 109, '20': 7, 'please': 651, 'understand': 896, 'keto in': 464, 'in the': 409, 'the past': 812, 'to try': 876, 'intermittent fasting': 419, 'trying to': 891, 'is my': 425, 'for the': 306, 'for my': 304, 'in my': 408, 'my life': 564, 'because it': 110, 'if you': 401, 'you can': 994, 'this is': 833, 'like to': 493, 'hey': 372, 'coming': 180, 'take': 775, 'they': 825, 'are': 85, 'ice': 394, 'cream': 195, 'friendly': 310, 'doesn': 224, 'to take': 873, 'they are': 826, 'keto friendly': 463, 'have to': 356, 'started': 743, 'weeks': 931, 'very': 913, 'thought': 841, 'loose': 505, 'mind': 542, 'sugar': 765, '16': 5, 'lbs': 482, 'don': 227, 'anything': 80, 'feeling': 282, 'better': 123, 'started keto': 744, 'of it': 600, 'and feel': 54, 'don have': 228, 'have any': 352, 'wondering': 970, 'kind': 471, 'find': 289, 'body': 130, 'run': 694, 'post': 654, 'months': 545, 'recently': 682, 'sure': 771, 'research': 689, 'running': 695, 'kept': 456, 'etc': 258, 'help': 367, 'thank': 782, 'advance': 25, 'wondering if': 971, 'there are': 822, 'keto diet': 460, 'kind of': 472, 'have been': 353, 'been on': 115, 'keto for': 462, 'for about': 300, 'on it': 619, 'it but': 439, 'to make': 865, 'carbs and': 158, 'thank you': 783, 'you all': 992, 'in advance': 406, 'problem': 662, 'alcohol': 31, 'working': 974, '10': 0, 'every': 261, 'other': 631, 'seem': 708, 'below': 120, 'ok': 613, 'progress': 665, 'daily': 201, 'time': 846, 'continue': 183, 'probably': 661, 'hit': 377, 'protein': 666, 'fats': 278, 'goals': 328, 'anyone': 77, 'experience': 267, 'and keto': 60, 'down to': 234, 'or so': 630, 'seem to': 709, 'to get': 856, 'question is': 670, 'going to': 330, 'protein and': 667, 'the day': 800, 'does anyone': 223, 'anyone have': 79, 'of this': 605, 'nsv': 592, '2019': 10, '40': 14, 'before': 116, 'done': 231, 'well': 938, 'loss': 510, 'bit': 126, 'thanks': 784, 'christmas': 171, 'from': 312, 'less': 485, 'than': 781, 'under': 895, 'feel like': 281, 'on the': 622, 'the weight': 817, 'weight loss': 937, 'but the': 144, 'from my': 313, 'less than': 486, 'this year': 838, 'wrong': 982, 'says': 702, 'sodium': 734, 'potassium': 656, 'magnesium': 524, 'total': 884, 'intake': 417, 'amount': 45, 'electrolytes': 250, 'we': 927, 'long': 499, 'been doing': 114, 'it is': 442, 'should be': 718, 'what is': 945, 'amount of': 46, 'don know': 229, 'use': 902, 'recipe': 683, 'sorry': 741, 'low': 517, 'carb': 156, 'found': 308, 'work': 972, 'low carb': 518, 'wanted': 916, 'start': 742, 're': 675, 'term': 779, 'due': 239, 'added': 24, 'remember': 688, 'last': 478, 'water': 923, 'heard': 363, 'people': 643, 'diets': 214, 'worked': 973, 'them': 819, 'thread': 843, 'seen': 711, 'why': 956, 'tracking': 886, 'wanted to': 917, 'to start': 871, 'but ve': 145, 'to help': 860, 'due to': 240, 'of weight': 607, 'the last': 807, 'doing keto': 226, 'and ve': 69, 'so that': 732, 'how to': 387, 'and can': 52, 'if anyone': 398, 'would be': 981, 'that are': 788, 'that you': 796, 'any tips': 75, 'blood': 128, 'test': 780, 'today': 877, 'were': 941, 'which': 951, 'two': 892, 'cholesterol': 170, 'has': 348, 'lower': 519, '200': 8, 'will': 959, 'avoid': 97, 'most': 551, 'else': 251, 'levels': 489, 'went to': 940, 'all of': 34, 'of the': 604, 'which is': 952, 'keto on': 466, 'can do': 155, 'snacks': 728, 'early': 244, 'until': 897, 'usually': 906, 'lunch': 520, 'hard': 346, 'home': 379, 'after': 27, 'hoping': 381, 'options': 628, 'between': 124, 'try to': 889, 'at work': 95, 'that can': 789, 'being': 118, 'used': 903, 'buy': 147, 'store': 755, 'lol': 498, 'used to': 904, 'keto but': 459, 'is there': 429, 'strict': 758, 'wife': 957, 'into': 420, 'our': 633, 'both': 131, 'scale': 703, 'weigh': 932, 'one': 625, 'then': 820, 'clothes': 173, 'her': 370, 'she': 715, 'quite': 674, 'top': 883, 'heavy': 365, 'huge': 392, 'favorite': 279, 'couldn': 188, 'see': 706, 'starting': 745, 'away': 98, 'us': 901, 'fat': 276, 'my wife': 569, 'the scale': 814, 'to see': 869, 'to have': 859, 'there is': 823, 'do it': 219, 'to go': 858, 'it for': 440, 'noticed': 589, 'stories': 756, 'said': 696, 'many': 529, 'ketosis': 470, 'deficit': 207, 'hours': 383, 'job': 451, 'cardio': 159, 'workout': 976, '30': 13, 'minutes': 543, 'fast': 274, 'around': 86, 'own': 639, 'couple': 190, 'symptoms': 774, 'flu': 295, 'absolutely': 21, 'stomach': 752, 'sick': 719, 'wasn': 921, 'keto flu': 461, 'but it': 140, 'salad': 697, 'amp': 47, 'bacon': 104, 'how do': 385, 'new': 578, 'fine': 290, 'its': 450, 'yet': 990, 'is that': 427, 'anyone else': 78, 'soon': 740, 'actually': 22, 'cut': 199, 'doctor': 221, 'quickly': 673, 'into the': 422, 'pics': 647, 'sw': 772, 'cw': 200, 'gw': 339, 'first': 291, 'https': 389, 'imgur': 403, 'com': 176, 'tired': 850, 'whatever': 947, 'through': 845, 'enough': 256, 'plan': 650, 'pretty': 660, 'healthy': 362, 'felt': 284, 'needed': 574, 'change': 162, 'changes': 164, 'head': 360, 'taking': 776, 'little': 495, 'finally': 288, 'haven': 357, '15': 4, 'worth': 979, 'energy': 254, 'omad': 616, 'weighed': 933, 'still': 751, 'made': 523, 'short': 716, 'look': 501, 'way': 925, 'count': 189, 'drink': 236, 'almost': 37, 'sweet': 773, 'another': 71, 'chocolate': 169, 'break': 134, 'ever': 260, 'already': 39, 'put': 668, 'where': 950, 'stuff': 761, 'everyone': 263, 'making': 527, 'right now': 693, 'now and': 591, 'to this': 875, 'https imgur': 390, 'imgur com': 404, 'and then': 67, 'all the': 35, 'working out': 975, 'it and': 437, 'the most': 808, 've lost': 910, 'all my': 33, 'me and': 533, 'and the': 66, 'but still': 143, 'of water': 606, 'and have': 56, 'for me': 302, 'as well': 88, 'and just': 59, 'get back': 320, 'bit of': 127, 'with my': 964, 'it to': 447, 'weight and': 935, 'and it': 58, 'is not': 426, 'goal': 326, 'pounds': 657, 'losing': 508, 'give': 322, 'idea': 395, 'makes': 526, 'zero': 999, 'goal weight': 327, 'months and': 547, 'my goal': 562, 'to lose': 864, 'up and': 899, 'my weight': 568, 'if this': 400, 'okay': 614, 'bought': 132, 'these': 824, 'beef': 112, 'net': 575, 'per': 644, 'stick': 749, 'without': 968, 'that it': 792, 'one of': 626, 'of ketosis': 602, 'dinner': 217, 'eggs': 248, 'side': 720, 'lifestyle': 491, 'happy': 345, 'of my': 603, 'can be': 154, 'let': 487, 'has anyone': 349, 'changed': 163, 'check': 166, 'problems': 663, 'able': 16, 'stay': 747, 'experienced': 268, 'ideas': 396, 'might': 540, 'losing weight': 509, 'able to': 17, 'to stay': 872, 'you have': 996, 'using': 905, 'from the': 314, 'is it': 424, 'it just': 443, 'fiber': 287, '20g': 11, 'ingredients': 413, 'such': 764, 'glucose': 323, 'level': 488, 'sleep': 725, '11': 2, 'you are': 993, 'of carbs': 597, 'you re': 997, 'net carbs': 576, 'the other': 811, 'to know': 863, 'hour': 382, 'old': 615, 'im': 402, '100': 1, 'numbers': 593, 'following': 296, 'calorie': 150, 'exercise': 266, 'morning': 550, 'information': 412, 'definitely': 208, 'ask': 89, 'those': 839, 'left': 484, 'others': 632, 'of eating': 598, 'and don': 53, 'the first': 804, 'my body': 559, 'the community': 799, 'more than': 549, 'help me': 368, 'snack': 727, 'suggestions': 766, 'possible': 653, 'but my': 141, 'ate': 96, 'by': 148, 'night': 582, 'seems': 710, 'thinking': 830, 'my own': 566, 'months ago': 546, 'ago and': 30, 'and was': 70, 'butter': 146, 'thanksgiving': 786, 'quick': 672, 'chicken': 168, 'next': 580, 'most of': 552, 'the time': 815, 'the next': 809, 'few days': 286, 'back into': 101, 'each': 243, 'some of': 736, 'will be': 960, 'know if': 475, 'saw': 700, 'products': 664, 'nuts': 595, 'drinking': 237, 'you guys': 995, 'go to': 325, 'super': 767, 'my keto': 563, 'with it': 962, 'milk': 541, 'tried': 887, 'same': 699, 'issues': 434, 'the same': 813, 'with this': 966, 'that my': 793, 'on how': 618, 'half': 343, 'seeing': 707, 'come': 178, 'but am': 138, 'any of': 74, 'of you': 608, 'overweight': 638, 'longer': 500, 'dropped': 238, 'back in': 100, 'couple of': 191, 'gain': 316, 'took': 882, 'regular': 687, 'difference': 215, 'anymore': 76, 'cause': 161, 'real': 679, 'dont': 232, 'weight but': 936, 'me to': 534, 'back to': 103, 'am not': 43, 'to do': 853, 'ketogenic': 468, 'journey': 452, 'was wondering': 920, 'posts': 655, 'similar': 721, 'guess': 337, 'it seems': 445, 'face': 270, 'thoughts': 842, 'the only': 810, 'has been': 350, 'what are': 943, 'supplements': 768, 'yesterday': 989, 'know what': 477, 'someone': 737, 'recipes': 684, 'have the': 355, 'x200b': 985, 'broccoli': 136, 'amp x200b': 48, 'later': 480, 'school': 704, 'need some': 572, 'up to': 900, 'and not': 62, 'not sure': 587, 'if it': 399, 'water weight': 924, 'tomorrow': 879, 'about it': 19, 'what do': 944, 'believe': 119, 'close': 172, 'motivation': 554, 'excited': 265, 'on my': 621, 'during the': 242, 'new to': 579, 'it would': 449, 'best': 122, '25': 12, 'into keto': 421, 'of fat': 599, 'curious': 197, 'enjoy': 255, 'cheese': 167, 'for keto': 301, 'questions': 671, 'it has': 441, 'helped': 369, 'struggling': 759, 'gave': 318, 'based': 106, 'that was': 795, 'and my': 61, 'what to': 946, 'don want': 230, 'to give': 857, 'on this': 623, 'the best': 798, 'to me': 866, 'way to': 926, 'crazy': 194, 'happened': 344, 'starting keto': 746, 'too much': 881, 'different': 216, 'appetite': 83, 'control': 184, 'this time': 836, 'at all': 91, 'had to': 342, 'two weeks': 893, 'my first': 561, 'this morning': 834, 'ketones': 469, 'my blood': 558, 'that is': 791, 'diet and': 213, 'hungry': 393, 'easy': 245, 'either': 249, 'however': 388, 'place': 649, 'macro': 521, 'grams': 334, 'gt': 336, 'male': 528, 'and some': 64, 'app': 82, 'when you': 949, 'cauliflower': 160, 'taste': 777, 'works': 977, 'www': 983, 'https www': 391, 'blood sugar': 129, 'share': 714, 'least': 483, 'fit': 293, 'at least': 92, 'the end': 802, 'end of': 253, 'set': 713, 'family': 271, 'everything': 264, 'worried': 978, 'info': 411, 'hope': 380, 'in ketosis': 407, 'first time': 292, 'nice': 581, 'sub': 762, 'keeping': 455, 'this sub': 835, 'every day': 262, '50': 15, 'hard to': 347, 'watch': 922, 'that have': 790, 'stick to': 750, 'fat and': 277, 'course': 192, 'benefits': 121, 'reading': 677, 'to find': 855, 'holidays': 378, 'gone': 331, 'nutrition': 594, 'in this': 410, 'sometimes': 739, 'knew': 473, 'to share': 870, 'this diet': 832, 'mean': 537, 'salt': 698, 'the way': 816, 've had': 909, 'know that': 476, 'for months': 303, 'is to': 431, 'but have': 139, 'especially': 257, 'instead': 414, 'because of': 111, 'add': 23, 'weekend': 930, 'stopped': 754, 'decided': 205, 'skin': 724, 'decided to': 206, 'time to': 847, 'cooking': 186, 'limit': 494, 'tell': 778, 'lots': 514, 'lots of': 515, 'nothing': 588, 'extra': 269, 'instead of': 415, 'breakfast': 135, 'came': 152, 'reddit': 685, 'size': 723, 'powder': 658, 'live': 496, 'it not': 444, 'to say': 868, 'he': 359, 'along': 38, 'per day': 645, 'him': 375, 'looked': 502, 'wiki': 958, 'support': 769, 'www reddit': 984, 'reddit com': 686, 'com keto': 177, 'keto wiki': 467, 'support thread': 770, 'last year': 479, 'about the': 20, 'it so': 446, 'cup': 196, 'self': 712, 'was the': 919, 'pressure': 659, 'pain': 640, 'and they': 68, 'ready': 678, '2018': 9, 'so ve': 733, 'that the': 794, 'person': 646, 'almond': 36, 'by the': 149, 'his': 376, 'flour': 294, 'thanks for': 785, 'story': 757, 'told': 878, 'dr': 235, 'this week': 837, 'vegetables': 911}

*TRANSFORM CORPUS*

In [14]:
keto_tf = cvec.transform(keto['titleself'])

In [15]:
keto_tf = pd.DataFrame(keto_tf.toarray(),
                          columns=cvec.get_feature_names())
keto_tf

,10,100,11,12,15,16,18,20,200,2018,...,yet,you,you all,you are,you can,you guys,you have,you re,your,zero
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,2,0,0,1,0,0,0,...,0,2,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,1,0,0,...,0,1,0,0,1,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7889,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7890,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7891,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
7892,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7893,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [16]:
keto_tf.to_csv('keto_transform.csv')

**ADDRESSING THE WINE DATAFRAME**

In [17]:
wine= pd.read_csv('wine_push_clean.csv')
wine.drop(columns = ['Unnamed: 0'],inplace=True)
wine.head()

,title,selftext,subreddit,created_utc,author,num_comments,score,is_self,timestamp
0,Looking for a summer job,"Hi,\n\nI'm a 23 year-old man from the Netherla...",wine,1580165102,Loirettoux,3,1,True,2020-01-27
1,California whites,"Whenever I try a Californian wine, it's always...",wine,1580170191,RaphGiroux,8,1,True,2020-01-27
2,Wine suggestions while in France (Provence),Will be traveling to France and spending most ...,wine,1580177480,irishmuse,4,1,True,2020-01-27
3,Show me the Munny Hunny | Wine Industry Report...,"If you are in the wine industry, congratulatio...",wine,1580177690,cudaeducation,0,1,True,2020-01-27
4,Going to Burgundy in May,"Hi, I'll be going to Burgundy during May and w...",wine,1580182920,GaanZi,5,1,True,2020-01-27

*FOCUS ON KEY COLUMNS*

In [18]:
wine.drop(columns=['created_utc','author','num_comments','score','is_self','timestamp'], inplace=True)

In [19]:
wine.head()

,title,selftext,subreddit
0,Looking for a summer job,"Hi,\n\nI'm a 23 year-old man from the Netherla...",wine
1,California whites,"Whenever I try a Californian wine, it's always...",wine
2,Wine suggestions while in France (Provence),Will be traveling to France and spending most ...,wine
3,Show me the Munny Hunny | Wine Industry Report...,"If you are in the wine industry, congratulatio...",wine
4,Going to Burgundy in May,"Hi, I'll be going to Burgundy during May and w...",wine

*CONVERT SUBREDDIT VALUE FOR WINE TO 2*

In [20]:
#subreddit is my target, which I will map to 0 for keto
wine['subreddit']=wine['subreddit'].map({'wine':2})

In [21]:
wine.head()

,title,selftext,subreddit
0,Looking for a summer job,"Hi,\n\nI'm a 23 year-old man from the Netherla...",2
1,California whites,"Whenever I try a Californian wine, it's always...",2
2,Wine suggestions while in France (Provence),Will be traveling to France and spending most ...,2
3,Show me the Munny Hunny | Wine Industry Report...,"If you are in the wine industry, congratulatio...",2
4,Going to Burgundy in May,"Hi, I'll be going to Burgundy during May and w...",2

In [22]:
wine['titleself']=wine['title']+' '+wine['selftext']
wine.head()

,title,selftext,subreddit,titleself
0,Looking for a summer job,"Hi,\n\nI'm a 23 year-old man from the Netherla...",2,"Looking for a summer job Hi,\n\nI'm a 23 year-..."
1,California whites,"Whenever I try a Californian wine, it's always...",2,California whites Whenever I try a Californian...
2,Wine suggestions while in France (Provence),Will be traveling to France and spending most ...,2,Wine suggestions while in France (Provence) Wi...
3,Show me the Munny Hunny | Wine Industry Report...,"If you are in the wine industry, congratulatio...",2,Show me the Munny Hunny | Wine Industry Report...
4,Going to Burgundy in May,"Hi, I'll be going to Burgundy during May and w...",2,"Going to Burgundy in May Hi, I'll be going to ..."

In [23]:
features = ['titleself']
X1=wine[features]
y1=wine.subreddit

In [24]:
# Assess y
y1.value_counts()

2    2882
Name: subreddit, dtype: int64

In [25]:
# Split the data into the training and testing sets.
X1_train, X1_test, y1_train, y1_test = train_test_split(X1,
                                                   y1,
                                                    test_size=0.33,
                                                    stratify=y1,
                                                   random_state=42)

In [26]:
cvec2=CountVectorizer(stop_words={'english'},max_features=1000,ngram_range=(1,2))

In [27]:
cvec2.fit(wine['titleself'])

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=1000, min_df=1,
                ngram_range=(1, 2), preprocessor=None, stop_words={'english'},
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [28]:
print(cvec2.vocabulary_)

{'looking': 480, 'for': 286, 'summer': 732, 'job': 437, 'hi': 364, 'year': 987, 'old': 562, 'from': 305, 'the': 765, 'working': 976, 'at': 102, 'wine': 938, 'bar': 110, 'and': 55, 'with': 964, 'of': 549, 'winery': 957, 'in': 399, 'france': 299, 'or': 579, 'italy': 435, 'to': 813, 'work': 975, 'could': 203, 'help': 359, 'tours': 850, 'some': 698, 'others': 583, 'if': 390, 'not': 542, 'interested': 407, 'any': 74, 'money': 507, 'just': 439, 'place': 606, 'stay': 719, 'learn': 452, 'about': 25, 'two': 857, 'weeks': 906, 'anyone': 82, 'has': 343, 'please': 611, 'let': 458, 'me': 497, 'know': 443, 'looking for': 482, 'from the': 306, 'with the': 968, 'for the': 294, 'interested in': 408, 'place to': 607, 'about wine': 28, 'wine for': 943, 'if anyone': 391, 'anyone has': 83, 'let me': 459, 'me know': 498, 'california': 166, 'whites': 928, 'try': 854, 'it': 423, 'always': 48, 'as': 96, 'my': 520, 'when': 919, 'is': 413, 'there': 784, 'better': 126, 'regions': 651, 'grapes': 331, 'down': 237, 'kind': 441, 'next': 535, 'trip': 852, 'store': 722, 'is there': 419, 'kind of': 442, 'for my': 291, 'trip to': 853, 'to the': 840, 'the wine': 778, 'suggestions': 730, 'while': 925, 'will': 934, 'be': 114, 'most': 513, 'time': 808, 'plan': 609, 'now': 546, 'pick': 603, 'up': 863, 'take': 737, 'us': 865, 'have': 346, 'style': 726, 'country': 204, 'side': 689, 'on': 563, 'wines': 958, 'options': 578, 'that': 754, 'are': 89, 'both': 139, 'ones': 571, 'only': 573, 'south': 707, 'greatly': 333, 'appreciated': 88, 'red': 643, 'but': 150, 'am': 49, 'well': 908, 'region': 650, 'rose': 660, 'will be': 935, 'most of': 514, 'of my': 551, 'is to': 421, 'wine in': 946, 'at the': 105, 'to have': 823, 'any suggestions': 81, 'wines to': 963, 'to be': 815, 'on the': 565, 'that are': 755, 'in the': 402, 'but am': 151, 'industry': 405, 'you': 990, 'friend': 303, 've': 873, 'found': 298, 'right': 657, 'such': 728, 'things': 794, 'how': 376, 'do': 226, 'amp': 52, 'much': 517, 'did': 221, 'sell': 676, '2019': 17, 'today': 844, 'wineries': 955, 'vs': 886, 'your': 997, 'vineyard': 878, 'lot': 484, 'information': 406, 'less': 457, 'than': 748, 'cost': 202, 'drink': 239, 'around': 95, 'these': 788, 'get': 313, 'state': 718, 'general': 311, 'welcome': 907, 'age': 37, 'https': 383, 'x200b': 986, 'if you': 395, 'the right': 775, 'how do': 377, 'is it': 414, 'how much': 379, 'and wine': 70, 'lot of': 485, 'about the': 27, 'amp x200b': 53, 'going': 323, 'burgundy': 148, 'may': 495, 'll': 475, 'during': 245, 'was': 891, 'wondering': 973, 'visit': 882, 'recommend': 638, 'they': 789, 'worth': 978, 'price': 618, 'especially': 255, 'cheers': 181, 'going to': 324, 'll be': 476, 'and was': 66, 'was wondering': 893, 'wondering if': 974, 'have to': 352, 'to visit': 842, 'the price': 774, 'more': 510, 'this': 799, 'so': 694, 'bought': 145, 'couple': 205, 'years': 988, 'ago': 40, '15': 3, 'him': 368, 'home': 370, 'cheap': 179, 'maybe': 496, 'what': 912, 'point': 612, 'tell': 746, 'thanks': 751, 'imgur': 397, 'com': 193, 'help me': 360, 'this wine': 801, 'couple of': 206, 'it just': 429, 'it is': 428, 'wine but': 941, 'what is': 915, 'is the': 418, 'that you': 764, 'about it': 26, 'https imgur': 384, 'imgur com': 398, 'recommendations': 640, 'good': 325, 'visiting': 884, 'places': 608, 'by': 161, 'available': 106, 'nice': 536, 'class': 188, 'who': 929, 'into': 410, 'recommendations on': 642, 'good wine': 326, 'by the': 162, 'for me': 290, 'me to': 499, 'to do': 817, 'to get': 820, 'into wine': 412, 'range': 630, 'almost': 45, 'everyone': 262, 'like': 463, 'must': 519, 'wines are': 960, 'question': 627, 'can': 168, 'make': 490, 'without': 971, 'them': 782, 'it in': 427, 'day': 212, 'ever': 260, 'done': 236, 'tour': 849, 'through': 807, 'would': 979, 'has anyone': 344, 'would you': 983, 'you recommend': 994, 'ideas': 389, 'tasting': 743, 'event': 259, 'first': 281, 'all': 42, 'say': 667, 'don': 233, 'type': 858, 'alcohol': 41, 'very': 877, 'new': 533, 'few': 276, 'months': 509, 'obviously': 548, 'food': 285, 'we': 896, 'getting': 314, 'stuff': 725, 'off': 559, 'keep': 440, 'people': 599, 'hours': 374, 'since': 691, 'never': 532, 'been': 119, 'before': 121, 'sure': 734, 'appreciate': 87, 'wine tasting': 950, 'this is': 800, 'new to': 534, 'to me': 831, 'as well': 99, 'have some': 350, 'to keep': 826, 'that the': 760, 'to wine': 843, 'not sure': 543, 'and would': 71, 'expensive': 266, 'cellar': 174, 'cool': 199, 'dark': 211, 'chateau': 178, 'bordeaux': 138, 'seen': 674, 'online': 572, 'thing': 793, 'what do': 914, 'are there': 93, 'for this': 295, 'start': 715, 'collection': 192, 'recently': 636, 'got': 328, 'rather': 631, 'something': 701, 'pair': 591, 'because': 118, 'want': 887, 'later': 451, 'out': 585, 'really': 635, 'fridge': 302, 'one': 569, 'long': 478, 'also': 47, 'should': 687, 'guys': 338, 'way': 894, 'how to': 380, 'to start': 837, 'want to': 888, 'the next': 771, 'out of': 586, 'wine fridge': 944, 'wine cellar': 942, 'you guys': 992, 'way to': 895, 'last': 450, 'after': 35, 'being': 122, 'thinking': 797, 'bottle': 140, 'over': 588, 'once': 568, 'heard': 357, 'does': 228, 'experience': 267, 'here': 362, 'how long': 378, 'but would': 158, 'would like': 981, 'like to': 466, 'the bottle': 768, 'does anyone': 229, 'anyone have': 84, 'asked': 101, 'questions': 628, 'away': 107, 'weekend': 905, 'think': 795, 'advance': 33, 'suggestions for': 731, 'bottle of': 142, 'of wine': 556, 'we are': 897, 've been': 874, 'wine that': 951, 'that is': 758, 'of the': 553, 'thanks in': 753, 'in advance': 400, '20': 4, 'title': 812, 'thank': 749, 'to pair': 834, 'thank you': 750, 'recommendation': 639, 'under': 860, 'huge': 387, 'coming': 196, 'her': 361, 'glass': 318, 'cab': 163, 'live': 473, 'based': 113, 'she': 682, 'likes': 469, 'dry': 243, 'notes': 544, 'had': 339, 'believe': 123, 'liked': 467, 'hoping': 372, 'find': 277, 'even': 258, 'hope': 371, 'hi all': 365, 'and want': 65, 'live in': 474, 'what the': 916, 'it was': 432, 'hoping to': 373, 'to find': 819, 'tips': 811, 'club': 191, 'interesting': 409, 'local': 477, 'shop': 684, 'every': 261, 'multiple': 518, 'left': 455, 'their': 781, 'an': 54, 'light': 462, 'our': 584, 'course': 207, 'else': 250, 'friends': 304, 'decided': 217, 'drinking': 241, 'which': 923, 'makes': 491, 'fun': 309, 'wine from': 945, 'we can': 898, 'in this': 403, 'and the': 62, 'the wines': 779, 'they have': 791, 'made': 489, 'champagne': 176, 'grand': 329, 'cru': 208, 'go': 320, 'group': 334, 'went': 910, 'week': 904, 'etc': 257, 'thought': 804, 'share': 681, 'community': 197, 'too': 845, 'each': 246, 'sort': 706, 'best': 125, 'french': 301, 'link': 470, 'www': 985, 're': 632, 'to help': 825, 'all of': 43, 'https www': 386, 'chardonnay': 177, 'specific': 712, 'tastings': 745, 'having': 354, 'single': 692, 'grape': 330, 'possible': 614, 'pretty': 617, 'set': 679, 'blanc': 133, 'de': 214, 'trying': 855, 'reddit': 648, 'full': 308, 'bottles': 143, 'wanted': 889, 'no': 538, 'and have': 58, 'to learn': 828, 'and we': 67, 'we re': 900, 'trying to': 856, 'the best': 767, 'into the': 411, 'for any': 288, 'any recommendations': 80, 'and if': 59, 'wanted to': 890, 'the most': 770, 'taking': 738, 'specifically': 713, 'small': 693, 'big': 128, 'producers': 622, 'and am': 56, 'there any': 785, 'looking to': 483, 'to go': 822, 'go to': 321, 'any of': 78, 'cabernet': 164, 'sauvignon': 665, 'tasted': 741, 'actually': 32, 'tastes': 742, 'ask': 100, '2017': 15, 'seem': 670, 'aging': 39, 'doesn': 230, 'taste': 740, 'bad': 109, 'flavor': 283, 'though': 803, 'cabernet sauvignon': 165, 'should be': 688, 'to ask': 814, 'seem to': 671, 'that it': 759, '200': 5, 'wife': 932, 'special': 711, 'gift': 315, 'favorite': 273, 'my wife': 523, 'wife and': 933, 'and are': 57, 'what are': 913, 'similar': 690, 'isn': 422, '60': 22, 'but can': 152, 'didn': 222, 'anyone know': 85, 'it to': 431, 'valley': 870, 'doing': 231, 'spain': 708, 'several': 680, 'days': 213, 'where': 920, 'room': 659, 'selection': 675, 'purchase': 623, 'case': 173, 'google': 327, 'seems': 672, 'book': 136, 'then': 783, 'give': 316, 'wine is': 947, 'is this': 420, 'it seems': 430, 'you have': 993, 'and then': 63, 'to taste': 839, 'can anyone': 169, 'im': 396, 'starting': 717, 'love': 486, 'his': 369, 'he': 355, 'between': 127, 'sweet': 735, 'different': 224, 'drank': 238, 'until': 862, 'started': 716, 'same': 664, 'soon': 705, 'port': 613, 'bit': 130, 'great': 332, 'wine and': 939, 'that was': 761, 'some of': 699, 'wine to': 952, 'the same': 776, 'my favorite': 521, 'bottles of': 144, 'to my': 832, 'think it': 796, 'restaurant': 654, 'buy': 159, 'per': 600, 'temperature': 747, 'open': 574, 'read': 633, 'need': 530, 'its': 436, 'idea': 388, 'fine': 279, 'to buy': 816, 'to make': 830, 'there are': 786, 'up to': 864, 'to open': 833, 'need to': 531, 'is not': 416, 'put': 625, 'look': 479, 'offer': 560, 'check': 180, 'one of': 570, 'as the': 98, 'to take': 838, 'you can': 991, 'can find': 171, 'curious': 209, 'using': 868, 'of these': 554, 'napa': 527, 'anything': 86, 'recommendations for': 641, 'experience with': 268, 'opened': 576, '2015': 13, 'haven': 353, 'yet': 989, 'les': 456, 'clos': 189, '100': 1, 'happy': 341, 'for an': 287, 'list': 471, 'already': 46, 'for some': 292, 'on my': 564, 'young': 996, 'beer': 120, 'part': 595, 'usually': 869, 'said': 661, 'variety': 872, 'probably': 620, '10': 0, 'given': 317, 'if this': 394, 'of wines': 557, 'wine as': 940, 'well as': 909, 'wines that': 962, 'any good': 76, 'would be': 980, 'oak': 547, 'currently': 210, 'second': 668, 'moscato': 512, 'other': 582, 'definitely': 218, 'white': 926, 'fan': 271, 'might': 504, 'three': 806, 'to try': 841, 'might be': 505, 'and it': 60, 'any other': 79, 'or two': 580, 'top': 847, '40': 20, 'hey': 363, 'month': 508, 'area': 94, 'enjoy': 252, 'hear': 356, 'has been': 345, 'to hear': 824, 'opening': 577, 'night': 537, 'difference': 223, 'for wine': 296, 'it would': 433, 'at all': 103, 'wset': 984, 'level': 460, 'little': 472, 'past': 598, 'tried': 851, 'still': 720, 'problem': 621, 'likely': 468, 'acidity': 30, 'finding': 278, 'merlot': 503, 'used': 867, 'whether': 922, 'bodied': 135, 'italian': 434, 'advice': 34, 'the first': 769, 'first time': 282, 'wine so': 949, 'but the': 156, 'if it': 392, 'red wine': 644, 'looking at': 481, 'they re': 792, 'don know': 235, 'where to': 921, 'any advice': 75, 'storage': 721, '50': 21, 'thoughts': 805, 'have any': 347, 'drinker': 240, 'bring': 146, 'family': 270, 'mind': 506, 'able': 23, 'be able': 115, 'able to': 24, 'to drink': 818, 'life': 461, 'nose': 541, 'sommelier': 703, 'many': 494, 'world': 977, 'in my': 401, 'in wine': 404, 'vintage': 880, 'quality': 626, 'learning': 453, 'person': 602, 've got': 875, 'do you': 227, 'you think': 995, 'hello': 358, 'end': 251, 'half': 340, '2016': 14, 'myself': 525, 'over the': 589, 'don have': 234, 'have the': 351, 'out there': 587, 'christmas': 185, 'use': 866, 'future': 310, 'that we': 762, 'pinot': 604, 'took': 846, 'to look': 829, 'all the': 44, 'business': 149, 'shops': 685, 'buying': 160, 'what to': 917, 'be in': 116, 'thinking of': 798, '30': 19, 'prefer': 616, 'least': 454, 'which is': 924, 'at least': 104, 'order': 581, '12': 2, 'domaine': 232, 'won': 972, 'free': 300, 'sales': 663, 'sonoma': 704, 'nothing': 545, 'we will': 902, 'and what': 68, 'was thinking': 892, 'see': 669, 'times': 810, 'comes': 195, 'come': 194, 'to see': 835, 'of you': 558, 'know what': 445, 'is that': 417, 'if there': 393, 'vineyards': 879, 'those': 802, 'often': 561, 'name': 526, 'mostly': 515, 'fruit': 307, 'own': 590, 'wineries in': 956, 'short': 686, 'post': 615, 'hi everyone': 366, 'part of': 596, 'time to': 809, '2013': 11, 'of this': 555, 've had': 876, 'but it': 154, 'it has': 426, 'my wine': 524, 'would love': 982, 'love to': 487, 'for good': 289, 'large': 449, 'stores': 723, 'wedding': 903, 'glasses': 319, 'particular': 597, 'however': 381, 'amazon': 51, 'thanks for': 752, 'exam': 264, 'back': 108, 'feel': 274, 'study': 724, 'knowledge': 446, 'palate': 594, 'books': 137, 'feel like': 275, 'making': 492, 'noir': 539, 'pinot noir': 605, 'goes': 322, 'service': 678, 'riesling': 656, 'above': 29, 'cork': 201, 'quite': 629, 'again': 36, 'natural': 528, 'http': 382, 'aged': 38, 'birthday': 129, 'as it': 97, 'below': 124, 'open to': 575, 'dinner': 225, 'for something': 293, 'something that': 702, 'are some': 91, 'house': 375, 'someone': 700, 'near': 529, 'hard': 342, 'why': 931, 'with wine': 969, 'that would': 763, 'blend': 134, 'certain': 175, 'another': 73, 'what would': 918, 'on this': 566, 'finish': 280, 'white wine': 927, 'budget': 147, 'value': 871, 'chianti': 183, 'but not': 155, 'wines and': 959, 'total': 848, 'generally': 312, '2012': 10, 'barolo': 111, 'decent': 216, 'more than': 511, 'bit of': 131, 'it for': 425, 'bottle and': 141, 'visited': 883, 'so much': 696, 'serve': 677, '2008': 6, '2011': 9, 'understand': 861, 'pairing': 592, '2018': 16, 'du': 244, 'wine pairing': 948, 'with it': 965, 'any help': 77, 'early': 247, 'were': 911, 'wine was': 953, 'on wine': 567, '2010': 8, 'came': 167, 'far': 272, 'perfect': 601, 'dessert': 219, 'with some': 967, 'to know': 827, 'sub': 727, 'planning': 610, 'have been': 348, 'the world': 780, 'and not': 61, 'of red': 552, 'are not': 90, 'across': 31, 'the us': 777, 'willing': 936, 'move': 516, 'red wines': 645, 'willing to': 937, 'sparkling': 710, 'vintages': 881, 'like the': 465, 'and will': 69, 'they are': 790, 'reviews': 655, 'and they': 64, 'spend': 714, 'to spend': 836, 'be the': 117, 'we ve': 901, 'shipping': 683, 'can be': 170, 'remember': 653, 'di': 220, 'wines from': 961, 'label': 448, 'of it': 550, 'it and': 424, 'that can': 756, 'pairings': 593, 'close': 190, 'enough': 254, 'tannins': 739, 'within': 970, 'decant': 215, 'high': 367, 'there is': 787, 'reading': 634, 'but have': 153, 'everything': 263, 'easy': 248, 'forward': 297, 'tasting notes': 744, 'the other': 773, 'your notes': 998, 'purchased': 624, 'cooler': 200, 'are the': 92, 'enjoyed': 253, 'either': 249, 'vivino': 885, 'have no': 349, 'that have': 757, 'reds': 649, 'considering': 198, 'guess': 337, 'but we': 157, 'we have': 899, 'super': 733, 'my first': 522, 'la': 447, '2014': 12, 'is my': 415, 'drunk': 242, 'private': 619, 'non': 540, 'focus': 284, 'know if': 444, '2009': 7, 'so far': 695, 'can get': 172, 'am looking': 50, 'so we': 697, 'relatively': 652, 'wine with': 954, 'with my': 966, 'uk': 859, 'suggest': 729, 'anniversary': 72, 'black': 132, 'spanish': 709, 'to give': 821, 'whole': 930, 'low': 488, 'sale': 662, 'rioja': 658, 'example': 265, 'fairly': 269, 'like it': 464, 'medium': 501, 'redd': 646, 'jpg': 438, 'redd it': 647, 'seems to': 673, 'menu': 502, 'city': 187, 'malbec': 493, 'château': 186, '25': 18, 'zinfandel': 999, 'estate': 256, 'the only': 772, 'meals': 500, 'recipe': 637, 'cheese': 182, 'gt': 335, 'chicken': 184, 'bars': 112, 'the area': 766, 'gt gt': 336, 'sauvignon blanc': 666, 'syrah': 736, 'https redd': 385}

*TRANSFORM CORPUS*

In [29]:
wine_tf = cvec.transform(wine['titleself'])

In [30]:
wine_tf = pd.DataFrame(wine_tf.toarray(),
                          columns=cvec.get_feature_names())
wine_tf

,10,100,11,12,15,16,18,20,200,2018,...,yet,you,you all,you are,you can,you guys,you have,you re,your,zero
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,5,0,1,0,0,0,0,2,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2877,0,1,0,0,0,0,0,0,0,0,...,1,1,0,0,0,0,0,0,0,0
2878,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
2879,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2880,1,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2881,1,0,0,2,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [31]:
wine_tf.to_csv('wine_transform.csv')

#### READING TRANSFORMED DATAFRAMES

In [32]:
df_k = pd.read_csv('keto_transform.csv')
df_k.drop(columns = ['Unnamed: 0'],inplace=True)
df_w = pd.read_csv('wine_transform.csv')
df_w.drop(columns = ['Unnamed: 0'],inplace=True)

In [33]:
df_k.head()

,10,100,11,12,15,16,18,20,200,2018,...,yet,you,you all,you are,you can,you guys,you have,you re,your,zero
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,2,0,0,1,0,0,0,...,0,2,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,1,0,0,...,0,1,0,0,1,0,0,0,1,0

In [34]:
df_k.shape

(7894, 1000)

In [35]:
df_w.head()

,10,100,11,12,15,16,18,20,200,2018,...,yet,you,you all,you are,you can,you guys,you have,you re,your,zero
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,5,0,1,0,0,0,0,2,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [36]:
df_w.shape

(2882, 1000)

## NEXT STEPS

- When to concatenate?
- Train test split next - Keto=train, wine=test?
- EDA